//! Kinds of local content that can be published to the federation.

use myriad_phantasi::ARTICLE_OBJECT_PREFIX;

/// `federation_published_content.content_type` of a quote-repost. It is listed
/// under 已发布 and can be withdrawn, but it is not a [`ContentKind`]: nothing
/// builds it from local content (see `interactions::announce_object`).
pub(crate) const REPOST_CONTENT_TYPE: &str = "repost";

/// A kind of local content with its own publisher, object URL family and
/// ActivityStreams type.
///
/// The string form is what `federation_published_content.content_type`, the
/// publish API's `content_type` and `mfp:contentType` carry. The frontend's
/// list of kinds is checked against `shared/federation_content_kinds.json`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ContentKind {
    Note,
    Report,
    PhantasiArticle,
    Tapp,
    Library,
}

impl ContentKind {
    pub const ALL: [Self; 5] = [
        Self::Note,
        Self::Report,
        Self::PhantasiArticle,
        Self::Tapp,
        Self::Library,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Note => "note",
            Self::Report => "report",
            Self::PhantasiArticle => "phantasi-article",
            Self::Tapp => "tapp",
            Self::Library => "library",
        }
    }

    /// ActivityStreams `type` of the published object.
    pub const fn ap_type(self) -> &'static str {
        match self {
            Self::Note => "Note",
            Self::Report | Self::PhantasiArticle => "Article",
            Self::Tapp => "Application",
            Self::Library => "Collection",
        }
    }

    /// Path of the object URL family, without the id segment.
    fn path_prefix(self) -> String {
        match self {
            Self::Note => "/notes".into(),
            Self::Report => "/reports".into(),
            // The same family as `myriad_phantasi::article_federation_path`.
            Self::PhantasiArticle => format!("{ARTICLE_OBJECT_PREFIX}/articles"),
            Self::Tapp => "/tapps".into(),
            Self::Library => "/library".into(),
        }
    }

    /// Canonical object URL for `id`. Tapp ids are free-form, so they are
    /// percent-encoded into a single path segment; the other kinds' ids are
    /// generated by us and emitted verbatim.
    pub fn object_url(self, base_url: &str, id: &str) -> String {
        let base_url = base_url.trim_end_matches('/');
        let prefix = self.path_prefix();
        match self {
            Self::Tapp => format!("{base_url}{prefix}/{}", urlencoding::encode(id)),
            _ => format!("{base_url}{prefix}/{id}"),
        }
    }

    /// Inverse of [`object_url`](Self::object_url): the kind and the stored
    /// content id of an object URL or bare path. The host is not checked —
    /// callers scope the lookup to their own rows. A query string or fragment
    /// is ignored; a Tapp id is percent-decoded.
    pub fn from_object_url(url: &str) -> Option<(Self, String)> {
        let path = url.split(['?', '#']).next().unwrap_or(url);
        let path = path.trim().trim_end_matches('/');
        let (parent, segment) = path.rsplit_once('/')?;
        if segment.is_empty() {
            return None;
        }
        // Every prefix starts with `/`, so `ends_with` matches whole segments.
        let parent = format!("/{}", parent.trim_start_matches('/'));
        let kind = Self::ALL
            .into_iter()
            .find(|kind| parent.ends_with(&kind.path_prefix()))?;
        let id = match kind {
            Self::Tapp => urlencoding::decode(segment).ok()?.into_owned(),
            _ => segment.to_string(),
        };
        Some((kind, id))
    }
}

impl std::fmt::Display for ContentKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl std::str::FromStr for ContentKind {
    type Err = String;

    fn from_str(raw: &str) -> Result<Self, Self::Err> {
        Self::ALL
            .into_iter()
            .find(|kind| kind.as_str() == raw)
            .ok_or_else(|| format!("unknown content kind: {raw}"))
    }
}

#[cfg(test)]
mod tests {
    use super::ContentKind;

    #[test]
    fn string_form_round_trips_and_matches_the_shared_contract() {
        for kind in ContentKind::ALL {
            assert_eq!(kind.as_str().parse::<ContentKind>(), Ok(kind));
        }
        assert!("announce".parse::<ContentKind>().is_err());
        assert!(super::REPOST_CONTENT_TYPE.parse::<ContentKind>().is_err());

        let shared: Vec<String> = serde_json::from_str(include_str!(
            "../../../../shared/federation_content_kinds.json"
        ))
        .expect("shared/federation_content_kinds.json");
        let ours: Vec<&str> = ContentKind::ALL.iter().map(|k| k.as_str()).collect();
        assert_eq!(shared, ours);
    }

    #[test]
    fn object_urls_round_trip_including_encoded_tapp_ids() {
        let base = "https://example.test/";
        let cases = [
            (
                ContentKind::Note,
                "note_1",
                "https://example.test/notes/note_1",
            ),
            (ContentKind::Report, "7", "https://example.test/reports/7"),
            (
                ContentKind::PhantasiArticle,
                "8",
                "https://example.test/phantasi/articles/8",
            ),
            (ContentKind::Library, "9", "https://example.test/library/9"),
            (ContentKind::Tapp, "demo", "https://example.test/tapps/demo"),
            (
                ContentKind::Tapp,
                "demo tapp",
                "https://example.test/tapps/demo%20tapp",
            ),
            (
                ContentKind::Tapp,
                "demo/tapp",
                "https://example.test/tapps/demo%2Ftapp",
            ),
            (
                ContentKind::Tapp,
                "名前?#%",
                "https://example.test/tapps/%E5%90%8D%E5%89%8D%3F%23%25",
            ),
        ];
        for (kind, id, url) in cases {
            assert_eq!(kind.object_url(base, id), url);
            assert_eq!(
                ContentKind::from_object_url(url),
                Some((kind, id.to_string()))
            );
        }
    }

    #[test]
    fn from_object_url_accepts_paths_and_ignores_query() {
        assert_eq!(
            ContentKind::from_object_url("/notes/n1/?x=1#frag"),
            Some((ContentKind::Note, "n1".into()))
        );
        assert_eq!(
            ContentKind::from_object_url("notes/n1"),
            Some((ContentKind::Note, "n1".into()))
        );
        assert_eq!(
            ContentKind::from_object_url("https://x.example/phantasi/articles/3"),
            Some((ContentKind::PhantasiArticle, "3".into()))
        );
        // `/articles` alone is not the Phantasi family; unknown families and
        // bare ids are not object URLs.
        assert_eq!(
            ContentKind::from_object_url("https://x.example/articles/3"),
            None
        );
        assert_eq!(
            ContentKind::from_object_url("https://x.example/snotes/3"),
            None
        );
        assert_eq!(ContentKind::from_object_url("note_1"), None);
        assert_eq!(
            ContentKind::from_object_url("https://x.example/notes/"),
            None
        );
    }

    #[test]
    fn ap_types() {
        assert_eq!(ContentKind::Note.ap_type(), "Note");
        assert_eq!(ContentKind::Report.ap_type(), "Article");
        assert_eq!(ContentKind::PhantasiArticle.ap_type(), "Article");
        assert_eq!(ContentKind::Tapp.ap_type(), "Application");
        assert_eq!(ContentKind::Library.ap_type(), "Collection");
    }
}
